# Generated by Django 6.0.5 on 2026-05-29 14:43

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=apps.documents.models.upload_path),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("uploaded_At", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Complete", "Complete"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Green", "Green"),
                            ("Yellow", "Yellow"),
                            ("Red", "Red"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("findings", models.JSONField(blank=True, null=True)),
                ("analyzed_At", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_By",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
