# Generated by Django 6.0.5 on 2026-06-14 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_templatedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatedocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='templatedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='templatedocument',
            name='file',
            field=models.FileField(storage='apps.documents.storage.baseline_storage', upload_to=''),
        ),
    ]
